### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ZontarZon** [judsonjames/manga_website#1]
- [ ] Figure out how and where storage of the manga pages will occur
- [ ] Decide on a finite criteria for image submission (jpg vs. png vs. pdf, image size, etc.)
- [ ] Remote host the website using a host (nginx/gunicorn/droplet, pythonanywhere, etc.)
- [ ] Fill up the About Us page, modeled after the old site
- [ ] Create a blog post system for the news page
